# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: check-ast
          - id: check-case-conflict
          - id: check-json
          - id: check-toml
          - id: check-vcs-permalinks
          - id: check-merge-conflict
          - id: check-yaml
            args: ["--allow-multiple-documents"]
          - id: destroyed-symlinks
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks: [id: python-check-blanket-noqa]
