name: Auto Black

on: [push]

jobs:
  autoblack:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v1

      - run: pip install black

      - name: autoblack_check
        id: black-check
        continue-on-error: true
        run: black --check --config pyproject.toml pymine_net

      - name: autoblack
        if: steps.black-check.outcome != 'success'
        run: |
          black --config pyproject.toml .
          git commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -am "apply black codestyle"
          git push
