name: isort
on: [push]

jobs:
    autoblack:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v1

            - run: pip install isort

            - name: isort_check
              id: isort-check
              continue-on-error: true
              run: isort --check .

            - name: isort_fix
              if: steps.isort-check.outcome != 'success'
              run: isort .

            - name: isort_publish
              if: steps.isort-check.outcome != 'success'
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git commit -am "apply import sorting"
                  git push
